- name: web server
  hosts: web
  
  tasks:
    - name: Install Nginx
      yum:
        name: nginx

    - name: Create Contents
      copy:
        src: ./html
        dest: /usr/share/nginx/
        mode: u=rw,g=r,o=r

    - name: Start Nginx service
      service:
        name: nginx
        state: restarted