- name: web server
  hosts: web
  
  tasks:
    - name: Install Nginx
      yum:
        name: nginx

    - name: Create Contents
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: preserve

    - name: Start Nginx service
      service:
        name: nginx
        state: restarted